import { Settings, Trash2 } from 'lucide-react'
import { App } from 'obsidian'
import React from 'react'

import {
  PLAN_PROVIDER_TYPES,
  getProviderTypeLabel,
} from '../../../constants'
import { useSettings } from '../../../contexts/settings-context'
import { getEmbeddingModelClient } from '../../../core/rag/embedding'
import SmartComposerPlugin from '../../../main'
import { LLMProvider } from '../../../types/provider.types'
import { useI18n } from '../../../utils/i18n'
import { ConfirmModal } from '../../modals/ConfirmModal'
import {
  AddProviderModal,
  EditProviderModal,
} from '../modals/ProviderFormModal'

type ProvidersSectionProps = {
  app: App
  plugin: SmartComposerPlugin
}

export function ProvidersSection({ app, plugin }: ProvidersSectionProps) {
  const { settings, setSettings } = useSettings()
  const { t, language } = useI18n()
  const isZh = language === 'zh'
  const apiProviders = settings.providers.filter(
    (p) => !PLAN_PROVIDER_TYPES.includes(p.type),
  )

  const handleDeleteProvider = async (provider: LLMProvider) => {
    // Get associated models
    const associatedChatModels = settings.chatModels.filter(
      (m) => m.providerId === provider.id,
    )
    const associatedEmbeddingModels = settings.embeddingModels.filter(
      (m) => m.providerId === provider.id,
    )

    const message = isZh
      ? `确定要删除服务商 "${provider.id}" 吗？\n\n` +
        `这同时会删除：\n` +
        `- ${associatedChatModels.length} 个对话模型\n` +
        `- ${associatedEmbeddingModels.length} 个嵌入模型\n\n` +
        `并且将清理数据库中使用关联嵌入模型生成的所有向量数据。`
      : `Are you sure you want to delete provider "${provider.id}"?\n\n` +
        `This will also delete:\n` +
        `- ${associatedChatModels.length} chat model(s)\n` +
        `- ${associatedEmbeddingModels.length} embedding model(s)\n\n` +
        `All vector data generated by these embedding models will also be cleared.`

    new ConfirmModal(app, {
      title: isZh ? '删除服务商' : 'Delete Provider',
      message: message,
      ctaText: isZh ? '删除' : 'Delete',
      onConfirm: async () => {
        const vectorManager = (await plugin.getDbManager()).getVectorManager()
        const embeddingStats = await vectorManager.getEmbeddingStats()

        // Clear embeddings for each associated embedding model
        for (const embeddingModel of associatedEmbeddingModels) {
          const embeddingStat = embeddingStats.find(
            (v) => v.model === embeddingModel.id,
          )

          if (embeddingStat?.rowCount && embeddingStat.rowCount > 0) {
            // only clear when there's data
            const embeddingModelClient = getEmbeddingModelClient({
              settings,
              embeddingModelId: embeddingModel.id,
            })
            if (embeddingModelClient) {
              await vectorManager.clearAllVectors(embeddingModelClient)
            }
          }
        }

        const remainingChatModels = settings.chatModels.filter(
          (v) => v.providerId !== provider.id,
        )
        const remainingEmbeddingModels = settings.embeddingModels.filter(
          (v) => v.providerId !== provider.id,
        )

        const isChatModelDeleted = !remainingChatModels.some(
          (m) => m.id === settings.chatModelId,
        )
        const isApplyModelDeleted = !remainingChatModels.some(
          (m) => m.id === settings.applyModelId,
        )
        const isEmbeddingModelDeleted = !remainingEmbeddingModels.some(
          (m) => m.id === settings.embeddingModelId,
        )

        await setSettings({
          ...settings,
          providers: settings.providers.filter((v) => v.id !== provider.id),
          chatModels: remainingChatModels,
          embeddingModels: remainingEmbeddingModels,
          chatModelId: isChatModelDeleted ? '' : settings.chatModelId,
          applyModelId: isApplyModelDeleted ? '' : settings.applyModelId,
          embeddingModelId: isEmbeddingModelDeleted ? '' : settings.embeddingModelId,
        })
      },
    }).open()
  }

  return (
    <div className="aide-settings-section">
      <div className="aide-settings-header">{t('settings.providers')}</div>

      <div className="aide-settings-desc">
        <span>{t('settings.providersDesc')}</span>
      </div>

      <div className="aide-settings-table-container">
        <table className="aide-settings-table">
          <colgroup>
            <col />
            <col />
            <col />
            <col width={60} />
          </colgroup>
          <thead>
            <tr>
              <th>{t('common.id')}</th>
              <th>{t('common.type')}</th>
              <th>{t('common.apiKey')}</th>
              <th>{t('common.actions')}</th>
            </tr>
          </thead>
          <tbody>
            {apiProviders.map((provider) => (
              <tr key={provider.id}>
                <td>{provider.id}</td>
                <td>{getProviderTypeLabel(provider.type, language)}</td>
                <td
                  className="aide-settings-table-api-key"
                  onClick={() => {
                    new EditProviderModal(app, plugin, provider).open()
                  }}
                >
                  {provider.apiKey ? '••••••••' : t('common.setApiKey')}
                </td>
                <td>
                  <div className="aide-settings-actions">
                    <button
                      onClick={() => {
                        new EditProviderModal(app, plugin, provider).open()
                      }}
                      className="clickable-icon"
                      title={t('common.edit')}
                    >
                      <Settings />
                    </button>
                    <button
                      onClick={() => handleDeleteProvider(provider)}
                      className="clickable-icon"
                      title={t('common.delete')}
                    >
                      <Trash2 />
                    </button>
                  </div>
                </td>
              </tr>
            ))}
          </tbody>
          <tfoot>
            <tr>
              <td colSpan={4}>
                <button
                  onClick={() => {
                    new AddProviderModal(app, plugin).open()
                  }}
                >
                  {t('settings.addCustomProvider')}
                </button>
              </td>
            </tr>
          </tfoot>
        </table>
      </div>
    </div>
  )
}
